# Generated by Django 6.0 on 2025-12-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_food_order_orderitem_table_delete_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='avaiable',
            new_name='available',
        ),
    ]
